spring:
  config:
    import: optional:file:./secret-clarifai.properties
  datasource:
    url: jdbc:h2:file:./data/facerecognition;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:h2/schema.sql
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console

clarifai:
  api:
    pat: ${CLARIFAI_API_PAT:}
    user-id: ${CLARIFAI_USER_ID:}
    app-id: ${CLARIFAI_APP_ID:}
