name: Backend SCA Scan

on:
  push:
    branches: ["vulnerabilities"]
  pull_request:

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk dependency scan
        env:
          SYNK_API: ${{ secrets.SYNK_API }}
        run: snyk test --all-projects --json > snyk_report.json

      - name: Upload Snyk report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk_report.json
